BackOfficeWeb/Controllers/BookingRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BackOfficeWeb.Models;
using AutoMapper;
using System.Text;
using Microsoft.AspNet.Identity;
using System.IO;
using log4net;
using Booking.Models;
using System.Web.Script.Serialization;
using Booking.Common;
using System.Configuration;
using Newtonsoft.Json;

namespace BackOfficeWeb.Controllers
{
    [Authorize]
    public class BookingRequestController : Controller
    {
        private readonly ILog _log;
        private readonly WebHelper _webHelper;

        public BookingRequestController(ILog log, WebHelper webHelper)
        {
            _log = log;
            _webHelper = webHelper;

            Mapper.CreateMap<BookingRequest, UpdateStatusViewModel>();
        }

        public ActionResult Index(int page = 0)
        {
            bool success;
            var response = _webHelper.GetResponse(string.Format("{0}/GetPendingBookingRequests?page={1}", ConfigurationManager.AppSettings["BookingWebApiUrl"], page), string.Empty, "GET", "text/json", out success);
            var result = JsonConvert.DeserializeObject<BookingListModel>(response);

            if (result == null)
            {
                return View();
            }

            SetPagingModel(page, result.TotalPages);

            return View(result.BookingRequests);
        }

        public ActionResult CheckStatus(string status, int page = 0)
        {
            bool success;
            var response = _webHelper.GetResponse(string.Format("{0}/GetStatus?status={1}&page={2}", ConfigurationManager.AppSettings["BookingWebApiUrl"], status, page), string.Empty, "GET", "text/json", out success);
            var result = JsonConvert.DeserializeObject<BookingListModel>(response);

            ViewData["statistics"] = GetBookingStatistics();

            if (result == null)
            {
                return View();
            }

            SetPagingModel(page, result.TotalPages);

            return View(result.BookingRequests);
        }

        public ActionResult ViewKpi(int page = 0)
        {
            bool success;
            var response = _webHelper.GetResponse(string.Format("{0}/GetBookingProcessKpi?page={1}", ConfigurationManager.AppSettings["BookingWebApiUrl"], page), string.Empty, "GET", "text/json", out success);
            var result = JsonConvert.DeserializeObject<BookingRequestKpiListModel>(response);

            if (result == null)
            {
                return View();
            }

            SetPagingModel(page, result.TotalPages);

            return View(result.BookingRequestKpis);
        }

        private void SetPagingModel(int currentPage, int totalPages)
        {
            ViewBag.PagingModel = new PagingModel
            {
                TotalPages = totalPages,
                CurrentPage = currentPage
            };
        }

        private BookingStatisticsModel GetBookingStatistics()
        {
            bool success;
            var response = _webHelper.GetResponse(string.Format("{0}/GetStatistics", ConfigurationManager.AppSettings["BookingWebApiUrl"]), string.Empty, "GET", "text/json", out success);
            var statistics = JsonConvert.DeserializeObject<BookingStatisticsModel>(response);

            return statistics;
        }
        
        public ActionResult Details(string id, bool process = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bool success;
            var response = _webHelper.GetResponse(string.Format("{0}/GetBookingRequest/{1}", ConfigurationManager.AppSettings["BookingWebApiUrl"], id), string.Empty, "GET", "text/json", out success);
            var bookingRequest = JsonConvert.DeserializeObject<BookingRequest>(response);

            if (bookingRequest == null)
            {
                return HttpNotFound();
            }
            var viewModel = new UpdateStatusViewModel();
            Mapper.Map<BookingRequest, UpdateStatusViewModel>(bookingRequest, viewModel);
            ViewBag.Process = process;

            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"];
            }

            return View(viewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateStatus(UpdateStatusViewModel model)
        {
            bool success;
            var json = JsonConvert.SerializeObject(new UpdateStatusModel { Status = model.Status, UpdatedBy = User.Identity.GetUserName(), ReplyMessage = model.ReplyMessage });
            
            _webHelper.GetResponse(string.Format("{0}/updatestatus/{1}", ConfigurationManager.AppSettings["BookingWebApiUrl"], model.RequestNumber), json, "POST", "text/json", out success);

            if (success)
            {
                return RedirectToAction("Index");
            }

            TempData["ErrorMessage"] = "Update Status Error!";
            return RedirectToAction("Details", new { id = model.RequestNumber, process = true });
        }
    }
}

BackOfficeWeb/Views/Shared/_Layout.cshtml
@using BackOfficeWeb.Resources
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Text.Global_ApplicationName</title>
    <link rel="shortcut icon" href="/content/images/favicon.ico" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a href="@Url.Action("Index", "Home")" class="navbar-brand"><img width="40" height="25" src="/content/images/logo.png" alt="Logo"> BackOffice</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                    <li class="dropdown">
                        <a id="dLabel" data-target="#" href="javascript:void(0)" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            @Text.Menu_Bookings
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li>@Html.ActionLink(Text.Menu_ProcessBookingRequests, "Index", "BookingRequest")</li>
                            <li>@Html.ActionLink(Text.Menu_ViewBookingRequests, "CheckStatus", "BookingRequest")</li>
                            <li>@Html.ActionLink(Text.Menu_ViewCallCenterKpi, "ViewKpi", "BookingRequest")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a id="dLabelLang" data-target="#" href="javascript:void(0)" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Language
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dLabelLang">
                            <li><a href="javascript:void(0)" class="lang" lang="en-gb"><img class="flag-icon" src="/content/images/icon-british-flag.jpg" /> English</a></li>
                            <li><a href="javascript:void(0)" class="lang" lang="th-th"><img class="flag-icon" src="/content/images/icon-thai-flag.gif" /> Thai</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Text.Global_ApplicationName</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $(".dropdown").hover(
                function () {
                    $('.dropdown-menu', this).stop(true, true).fadeIn("fast");
                    $(this).toggleClass('open');
                    $('b', this).toggleClass("caret caret-up");
                },
                function () {
                    $('.dropdown-menu', this).stop(true, true).fadeOut("fast");
                    $(this).toggleClass('open');
                    $('b', this).toggleClass("caret caret-up");
            });

            $(".lang").click(function () {
                window.location.href = window.location.href.replace("en-gb", $(this).attr("lang")).replace("th-th", $(this).attr("lang"));
            });
        });
    </script>
</body>
</html>